### PR TITLE
Add more tests and fix bugs

### LINKED ISSUE #122: Documenter issue with docstring
There is an issue with the docstring of `ClimaDiagnostics.Writers.NetCDFWriter(space, output_dir; num_points, sync_schedule, z_sampling_method)`.

Image

### PR DESCRIPTION
**Pull request by ph-kev**
closes #122 - This PR adds more tests for `Writers.target_coordinates` and `Writers.hcoords_from_horizontal_space`. Furthermore, this PR also fix a bug when working with a box domain as `num_points` was being interpreted as Lat-Long-Z instead of Long-Lat-Z. Finally, the latest version of Documenter is used and ClimaCore is added as a dependency to make the documentation for NetCDFWriter available to Documenter.

### CODE REVIEW

File: test/writers.jl [hunk 1]
```diff
@@ -38,6 +39,124 @@ output_dir = mktempdir(pwd())
...
+    @test size(hcoords) == (NUM, 2NUM)
+    @test hcoords ==
+          [Geometry.LatLongPoint(lat, lon) for lon in lons, lat in lats]
+
+    hpts, vpts = Writers.target_coordinates(
+        space,
+        (NUM, 2NUM, 3NUM),
+        ClimaDiagnostics.Writers.LevelsMethod(),
+    )
+    lon, lat = hpts
```
Comment (imreddyTeja) [inline test/writers.jl]:
```suggestion
    lons, lats = hpts
```

File: src/netcdf_writer_coordinates.jl [hunk 2]
```diff
@@ -329,7 +329,7 @@ function target_coordinates(
     else
         ypts = collect(range(ymin, ymax, num_points_y))
     end
-    return (xpts, ypts)
+    return islatlonbox(domain) ? (ypts, xpts) : (xpts, ypts)
```
Comment (imreddyTeja) [inline src/netcdf_writer_coordinates.jl]: Could you add a comment explaining why this is done? The comments on lines 310-311 explain it, but reasoning through this function was hard for me. I think this might be more readable if we duplicated the code, and used lat/lon variable names for the latlonbox case, and xy for the other case.
